name: Publish to DigitalOcean
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup SBT
        uses: JTalk/setup-sbt@v1
        with:
          version: '1.11.6'

      - name: Compile and Test
        run: sbt clean compile test


